In [1]:
import numpy as np

In [2]:
numbers= np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b=np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
c= np.arange(13,53)

In [6]:
c

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52])

In [7]:
c[4]

17

In [8]:
c[6:]

array([19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52])

In [9]:
c[:11]

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [10]:
c[7:15]

array([20, 21, 22, 23, 24, 25, 26, 27])

In [11]:
c.mean()

32.5

In [12]:
numbers.mean()

4.5

In [13]:
b.mean()

4.5

In [14]:
c.sum()

1300

In [16]:
c.std()

11.543396380615196

In [17]:
c.var()

133.25